//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;
using Project.DAL.FactoryClasses;
using Project.DAL;

namespace Project.DAL.HelperClasses
{
	/// <summary>Field Creation Class for entity VehicleMakeEntity</summary>
	public partial class VehicleMakeFields
	{
		/// <summary>Creates a new VehicleMakeEntity.Abrv field instance</summary>
		public static EntityField2 Abrv
		{
			get { return (EntityField2)EntityFieldFactory.Create(VehicleMakeFieldIndex.Abrv);}
		}
		/// <summary>Creates a new VehicleMakeEntity.Id field instance</summary>
		public static EntityField2 Id
		{
			get { return (EntityField2)EntityFieldFactory.Create(VehicleMakeFieldIndex.Id);}
		}
		/// <summary>Creates a new VehicleMakeEntity.Name field instance</summary>
		public static EntityField2 Name
		{
			get { return (EntityField2)EntityFieldFactory.Create(VehicleMakeFieldIndex.Name);}
		}
	}

	/// <summary>Field Creation Class for entity VehicleModelEntity</summary>
	public partial class VehicleModelFields
	{
		/// <summary>Creates a new VehicleModelEntity.Abrv field instance</summary>
		public static EntityField2 Abrv
		{
			get { return (EntityField2)EntityFieldFactory.Create(VehicleModelFieldIndex.Abrv);}
		}
		/// <summary>Creates a new VehicleModelEntity.Id field instance</summary>
		public static EntityField2 Id
		{
			get { return (EntityField2)EntityFieldFactory.Create(VehicleModelFieldIndex.Id);}
		}
		/// <summary>Creates a new VehicleModelEntity.MakeId field instance</summary>
		public static EntityField2 MakeId
		{
			get { return (EntityField2)EntityFieldFactory.Create(VehicleModelFieldIndex.MakeId);}
		}
		/// <summary>Creates a new VehicleModelEntity.Name field instance</summary>
		public static EntityField2 Name
		{
			get { return (EntityField2)EntityFieldFactory.Create(VehicleModelFieldIndex.Name);}
		}
	}
	

}