//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Project.DAL.HelperClasses
{
	
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	
	
	/// <summary>Singleton implementation of the FieldInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	/// <remarks>It uses a single instance of an internal class. The access isn't marked with locks as the FieldInfoProviderBase class is threadsafe.</remarks>
	internal static class FieldInfoProviderSingleton
	{
		#region Class Member Declarations
		private static readonly IFieldInfoProvider _providerInstance = new FieldInfoProviderCore();
		#endregion

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static FieldInfoProviderSingleton()
		{
		}

		/// <summary>Gets the singleton instance of the FieldInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IFieldInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the FieldInfoProvider. Used by singleton wrapper.</summary>
	internal class FieldInfoProviderCore : FieldInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="FieldInfoProviderCore"/> class.</summary>
		internal FieldInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitVehicleMakeEntityInfos();
			InitVehicleModelEntityInfos();

			this.ConstructElementFieldStructures(InheritanceInfoProviderSingleton.GetInstance());
		}

		/// <summary>Inits VehicleMakeEntity's FieldInfo objects</summary>
		private void InitVehicleMakeEntityInfos()
		{
			this.AddFieldIndexEnumForElementName(typeof(VehicleMakeFieldIndex), "VehicleMakeEntity");
			this.AddElementFieldInfo("VehicleMakeEntity", "Abrv", typeof(System.String), false, false, false, false,  (int)VehicleMakeFieldIndex.Abrv, 20, 0, 0);
			this.AddElementFieldInfo("VehicleMakeEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)VehicleMakeFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("VehicleMakeEntity", "Name", typeof(System.String), false, false, false, false,  (int)VehicleMakeFieldIndex.Name, 20, 0, 0);
		}
		/// <summary>Inits VehicleModelEntity's FieldInfo objects</summary>
		private void InitVehicleModelEntityInfos()
		{
			this.AddFieldIndexEnumForElementName(typeof(VehicleModelFieldIndex), "VehicleModelEntity");
			this.AddElementFieldInfo("VehicleModelEntity", "Abrv", typeof(System.String), false, false, false, false,  (int)VehicleModelFieldIndex.Abrv, 20, 0, 0);
			this.AddElementFieldInfo("VehicleModelEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)VehicleModelFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("VehicleModelEntity", "MakeId", typeof(System.Int32), false, true, false, false,  (int)VehicleModelFieldIndex.MakeId, 0, 0, 10);
			this.AddElementFieldInfo("VehicleModelEntity", "Name", typeof(System.String), false, false, false, false,  (int)VehicleModelFieldIndex.Name, 20, 0, 0);
		}
		
	}
}




