//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Data;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Project.DAL.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	/// <remarks>It uses a single instance of an internal class. The access isn't marked with locks as the PersistenceInfoProviderBase class is threadsafe.</remarks>
	internal static class PersistenceInfoProviderSingleton
	{
		#region Class Member Declarations
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();
		#endregion

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton()
		{
		}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitVehicleMakeEntityMappings();
			InitVehicleModelEntityMappings();
		}

		/// <summary>Inits VehicleMakeEntity's mappings</summary>
		private void InitVehicleMakeEntityMappings()
		{
			this.AddElementMapping("VehicleMakeEntity", @"Vehicle", @"dbo", "VehicleMake", 3, 0);
			this.AddElementFieldMapping("VehicleMakeEntity", "Abrv", "Abrv", false, "NVarChar", 20, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("VehicleMakeEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("VehicleMakeEntity", "Name", "Name", false, "NVarChar", 20, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits VehicleModelEntity's mappings</summary>
		private void InitVehicleModelEntityMappings()
		{
			this.AddElementMapping("VehicleModelEntity", @"Vehicle", @"dbo", "VehicleModel", 4, 0);
			this.AddElementFieldMapping("VehicleModelEntity", "Abrv", "Abrv", false, "NVarChar", 20, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("VehicleModelEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("VehicleModelEntity", "MakeId", "MakeId", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("VehicleModelEntity", "Name", "Name", false, "NVarChar", 20, 0, 0, false, "", null, typeof(System.String), 3);
		}

	}
}
