// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Project.DAL.Models;
using System;

namespace Project.DAL.Migrations
{
    [DbContext(typeof(VehicleContext))]
    [Migration("20180628013135_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project.DAL.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Price");

                    b.Property<int>("Quantity");

                    b.Property<string>("UserName");

                    b.Property<string>("VehicleMake");

                    b.Property<string>("VehicleModel");

                    b.Property<int>("VehiclesForSaleId");

                    b.HasKey("Id");

                    b.HasIndex("VehiclesForSaleId");

                    b.ToTable("Cart");
                });

          

            modelBuilder.Entity("Project.DAL.Models.ItemsInStockModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ItemsInStock");

                    b.Property<int>("VehiclesForSaleId");

                    b.HasKey("Id");

                    b.HasIndex("VehiclesForSaleId")
                        .IsUnique();

                    b.ToTable("ItemsInStockModel");
                });

          

            modelBuilder.Entity("Project.DAL.Models.VehiclesForSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Price");

                    b.Property<string>("VehicleMake");

                    b.Property<string>("VehicleModel");

                    b.Property<byte[]>("VehiclePicture");

                    b.HasKey("Id");

                    b.ToTable("VehiclesForSale");
                });

            modelBuilder.Entity("Project.DAL.Models.Cart", b =>
                {
                    b.HasOne("Project.DAL.Models.VehiclesForSale", "VehiclesForSale")
                        .WithMany("Cart")
                        .HasForeignKey("VehiclesForSaleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Project.DAL.Models.ItemsInStockModel", b =>
                {
                    b.HasOne("Project.DAL.Models.VehiclesForSale", "VehiclesForSale")
                        .WithOne("ItemsInStockModel")
                        .HasForeignKey("Project.DAL.Models.ItemsInStockModel", "VehiclesForSaleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

           
#pragma warning restore 612, 618
        }
    }
}
