//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Collections.Generic;
using Project.DAL;
using Project.DAL.FactoryClasses;
using Project.DAL.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Project.DAL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: VehicleModel. </summary>
	public partial class VehicleModelRelations
	{
		/// <summary>CTor</summary>
		public VehicleModelRelations()
		{
		}

		/// <summary>Gets all relations of the VehicleModelEntity as a list of IEntityRelation objects.</summary>
		/// <returns>a list of IEntityRelation objects</returns>
		public virtual List<IEntityRelation> GetAllRelations()
		{
			List<IEntityRelation> toReturn = new List<IEntityRelation>();
			toReturn.Add(this.VehicleMakeEntityUsingMakeId);
			return toReturn;
		}

		#region Class Property Declarations



		/// <summary>Returns a new IEntityRelation object, between VehicleModelEntity and VehicleMakeEntity over the m:1 relation they have, using the relation between the fields:
		/// VehicleModel.MakeId - VehicleMake.Id
		/// </summary>
		public virtual IEntityRelation VehicleMakeEntityUsingMakeId
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne, "VehicleMake", false);
				relation.AddEntityFieldPair(VehicleMakeFields.Id, VehicleModelFields.MakeId);
				relation.InheritanceInfoPkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("VehicleMakeEntity", false);
				relation.InheritanceInfoFkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("VehicleModelEntity", true);
				return relation;
			}
		}
		/// <summary>stub, not used in this entity, only for TargetPerEntity entities.</summary>
		public virtual IEntityRelation GetSubTypeRelation(string subTypeEntityName) { return null; }
		/// <summary>stub, not used in this entity, only for TargetPerEntity entities.</summary>
		public virtual IEntityRelation GetSuperTypeRelation() { return null;}
		#endregion

		#region Included Code

		#endregion
	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticVehicleModelRelations
	{
		internal static readonly IEntityRelation VehicleMakeEntityUsingMakeIdStatic = new VehicleModelRelations().VehicleMakeEntityUsingMakeId;

		/// <summary>CTor</summary>
		static StaticVehicleModelRelations()
		{
		}
	}
}
